pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                echo "bbb"
                echo "111"
                echo "2222"
                echo "333333"
                echo "4"
            }
        }
    }
}
