pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                echo "bbb"
                echo "111"
                echo "222"
                echo "3333"
            }
        }
    }
}
