pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                echo "aaa"
                echo "111"
                echo "2222"
                echo "3"
                echo "44"
            }
        }
    }
}
