pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                echo "aaa"
                echo "111"
                echo "2222"
                echo "333"
                echo "4444"
                echo "5"
            }
        }
    }
}
